### PR TITLE
add hungarian translation

### PR DESCRIPTION
**Pull request by milli05**
Added hungarian translation

### CODE REVIEW

**Comment by hiddenpearls** [comment]
Thanks @milli05 

Do you use WordPress? Even made an account at WordPress.org?

**Comment by milli05** [comment]
I personally do not have a wordpress site, but we develop wp sites at my workplace.

**Comment by hiddenpearls** [comment]
awesome @milli05

**Comment by hiddenpearls** [comment]
@milli05 I will merge your pull request.
Would you please do translation on https://translate.wordpress.org/projects/wp-plugins/wp-analytify?

**Pull request merged**
